catalog page and updates
Exordium-Project/e-shop pull request #21
Opened 2022-06-08 19:00 UTC by IvayloSlavchev

2022-06-09 06:56 UTC, petya0111 commented on client/src/components/Header/Catalog/Catalog.js
> +                        <Button className='catalog-btns secondButtonWidth'>
let's have more descriptive names and not 'firstButtonWidth', 'secondButtonWidth' ..

2022-06-09 07:31 UTC, petya0111 commented on client/src/components/Header/Catalog/SideBar.js
> +                    <Box className='side-bar-boxes'>
try to separate this  <Box className='side-bar-boxes'> in separate component to not have repeated code

2022-06-09 17:26 UTC, IvayloSlavchev commented on client/src/components/Header/Catalog/Catalog.js
> +                        <Button className='catalog-btns secondButtonWidth'>
Fixed

2022-06-09 17:26 UTC, IvayloSlavchev commented on client/src/components/Header/Catalog/SideBar.js
> +                    <Box className='side-bar-boxes'>
Fixed

2022-06-09 20:30 UTC, Arabadzhiew approved these changes

2022-06-10 06:55 UTC, JordanRad approved these changes

2022-06-10 07:33 UTC, petya0111 approved these changes

2022-06-10 08:13 UTC, petya0111 commented
@IvayloSlavchev  try to use Material UI Grid functionality to achieve a responsive sidebar and navbar :)

2022-06-10 08:13 UTC, petya0111 reviewed
@IvayloSlavchev try to use Material UI Grid functionality to achieve a responsive sidebar and navbar :)

2022-06-10 11:51 UTC, petya0111 requested changes
@IvayloSlavchev  try to use Material UI Grid functionality to achieve a responsive sidebar and navbar :)

2022-06-11 14:12 UTC, merged