Ex34/create main page layout
Exordium-Project/e-shop pull request #27
Opened 2022-06-12 13:33 UTC by fbozhkov

2022-06-12 14:13 UTC, JordanRad requested changes

2022-06-12 14:13 UTC, JordanRad commented on client/src/components/main-layout/mainPage.js
> +                        </Grid>
Please, use an array instead

2022-06-12 14:13 UTC, JordanRad commented on client/src/components/main-layout/mainPage.js
> +                                </Grid>
Same here

2022-06-12 15:31 UTC, petya0111 requested changes

2022-06-12 15:31 UTC, petya0111 commented on client/src/components/main-layout/mainPage.scss
> +    max-width: 1536px; // equal to background image width
fixed width can make problems in responsive views

2022-06-12 18:11 UTC, IvayloSlavchev requested changes
Clean your comments and the code in scss files that you're not going to use.

2022-06-14 08:51 UTC, fbozhkov commented
fixed

2022-06-14 13:28 UTC, JordanRad approved these changes
LGTM

2022-06-14 18:34 UTC, petya0111 approved these changes
Fully functional and responsive, good to go!  ✔️

2022-06-14 18:49 UTC, IvayloSlavchev approved these changes
LGTM!

2022-06-14 18:51 UTC, merged