Register/login functionality
Exordium-Project/e-shop pull request #29
Opened 2022-06-14 15:23 UTC by nyazadzhiev

2022-06-14 19:01 UTC, petya0111 requested changes

2022-06-14 19:01 UTC, petya0111 commented on server/controllers/Users.js
> +        password: req.body.password
1. you can extend the registration endpoint logic, for example for the field password to be validated with regex to have lowercase, uppercase, and special characters
2. resolve conflicts from the last merge

2022-06-15 11:13 UTC, JordanRad requested changes

2022-06-15 11:13 UTC, JordanRad commented on server/controllers/Users.js
> +    })
This should be part of the service layer. Please, use UserService for that or create it if it's not initialised yet

2022-06-15 11:13 UTC, JordanRad commented on server/server.js
> +}
Export this in a separate configuration in the ```/config``` folder. Use [this](https://github.com/Exordium-Project/e-shop/blob/dev/server/config/db.config.js) as a reference

2022-06-15 19:19 UTC, petya0111 approved these changes

2022-06-16 06:07 UTC, JordanRad approved these changes

2022-06-16 06:07 UTC, JordanRad commented on server/server.js
> +    secret: 'thisshouldbeabettersecret!',
Please, set the secret in the .env file and read it from the file.

2022-06-16 14:44 UTC, merged