Sign up
Exordium-Project/e-shop pull request #32
Opened 2022-06-18 17:54 UTC by IvayloSlavchev

2022-06-19 09:55 UTC, petya0111 requested changes
...

2022-06-19 10:09 UTC, petya0111 requested changes

2022-06-19 10:09 UTC, petya0111 commented on client/src/components/SignUp/SignUpStyles/Mobile-phone-view.scss
> +        position: relative;
why all of the positioned elements are on relative positions? In the mobile view, it doesn't look fine. Try to improve it with grid or something not so hardcoded. 
[https://ibb.co/B4GLqdL](url)

2022-06-19 10:09 UTC, petya0111 commented on client/src/components/SignUp/Inputs.js
> +                    <Button className='google-signUp'><GoogleIcon className='google-icon' /> Continue with Google</Button>
I see that something makes these button texts to be uppercase, find out why it happens.

2022-06-19 11:12 UTC, JordanRad commented on client/src/components/SignUp/Inputs.js
> +                    <Button className='google-signUp'><GoogleIcon className='google-icon' /> Continue with Google</Button>
MUI buttons are always uppercase, I think

2022-06-19 11:15 UTC, JordanRad requested changes

2022-06-19 11:15 UTC, JordanRad commented on client/src/components/SignUp/SignUpStyles/Mobile-phone-view.scss
> +        position: relative;
You can use the default MUI Sign up page and style it a little bit instead . You can refer to this link - https://mui.com/material-ui/getting-started/templates/

2022-06-19 11:15 UTC, JordanRad commented on client/src/components/SignUp/SignUpStyles/Registration-inputs.scss
> +    }
Please, do not overwrite MUI classes

2022-06-22 15:12 UTC, IvayloSlavchev commented on client/src/components/SignUp/SignUpStyles/Mobile-phone-view.scss
> +        position: relative;
Fixed

2022-06-22 15:13 UTC, IvayloSlavchev commented on client/src/components/SignUp/Inputs.js
> +                    <Button className='google-signUp'><GoogleIcon className='google-icon' /> Continue with Google</Button>
Fixed

2022-06-22 15:13 UTC, IvayloSlavchev commented on client/src/components/SignUp/SignUpStyles/Registration-inputs.scss
> +    }
Fixed

2022-06-22 15:16 UTC, petya0111 approved these changes
Nice responsive sign-up component ✔️

2022-06-22 20:52 UTC, JordanRad approved these changes

2022-06-23 16:38 UTC, merged