Added getAllProducts method to ProductService
Exordium-Project/e-shop pull request #38
Opened 2022-07-09 14:13 UTC by IvayloSlavchev

2022-07-09 15:25 UTC, petya0111 requested changes

2022-07-09 15:25 UTC, petya0111 commented on server/services/ProductService.js
> +            attributes: ['id', 'name', 'color', 'price', 'quantity', 'brand_id', 'type_id']
Are you sure we can search by all of these attributes here? see TypeService>getAllTypes example https://github.com/Exordium-Project/e-shop/blob/d2c0dd0bfedcd141de5caf7170ecd0dd64afd95d/server/services/TypeService.js

2022-07-10 11:49 UTC, JordanRad approved these changes

2022-07-10 17:07 UTC, petya0111 commented on server/services/ProductService.js
> +            attributes: ['id', 'name', 'color', 'price', 'quantity', 'brand_id', 'type_id']
If someday we can find solution we can improve it

2022-07-10 17:08 UTC, petya0111 approved these changes

2022-07-10 17:08 UTC, merged