Connected SignUp component with BackEnd and fixed some issues
Exordium-Project/e-shop pull request #41
Opened 2022-07-13 13:53 UTC by IvayloSlavchev

2022-07-13 17:28 UTC, Arabadzhiew commented on client/src/components/SignIn/SignIn.js
> +                                onChange={(e) => setUsernameOrEmail(e.target.value)}
Use more expressive variable/argument names. Generally speaking, single character names are not a good practice.

2022-07-13 17:32 UTC, Arabadzhiew requested changes

2022-07-13 17:32 UTC, Arabadzhiew commented on client/src/components/SignIn/SignIn.js
> +                                onChange={(e) => setUsernameOrEmail(e.target.value)}
Please use more expressive argument/variable names. Generally speaking, single character names are not a good practice.

2022-07-13 17:32 UTC, Arabadzhiew commented on client/src/components/SignIn/SignIn.js
> +                                onChange={(e) => setPassword(e.target.value)}
Same as above.

2022-07-13 17:32 UTC, Arabadzhiew commented on client/src/components/SignUp/Inputs.js
> +                            onChange={(e) => setFirstName(e.target.value)}
Same as above.

2022-07-13 17:32 UTC, Arabadzhiew commented on client/src/components/SignUp/Inputs.js
> +                            onChange={(e) => setLastName(e.target.value)}
Same as above.

2022-07-13 17:32 UTC, Arabadzhiew commented on client/src/components/SignUp/Inputs.js
> +                            onChange={(e) => setEmailReg(e.target.value)}
Same as above.

2022-07-13 17:32 UTC, Arabadzhiew commented on client/src/components/SignUp/Inputs.js
> +                            onChange={(e) => setUsernameReg(e.target.value)}
Same as above.

2022-07-13 17:32 UTC, Arabadzhiew commented on client/src/components/SignUp/Inputs.js
> +                            onChange={(e) => setPasswordReg(e.target.value)}
Same as above.

2022-07-14 05:34 UTC, petya0111 requested changes

2022-07-14 05:34 UTC, petya0111 commented on client/src/components/SignIn/SignIn.js
> +                                onChange={(e) => setUsernameOrEmail(e.target.value)}
I think usernameOrEmail is not correct because we have separate field for username and separate for the email in the database? @IvayloSlavchev @Arabadzhiew

2022-07-14 05:38 UTC, IvayloSlavchev commented on client/src/components/SignIn/SignIn.js
> +                                onChange={(e) => setUsernameOrEmail(e.target.value)}
Yeah, I forgot to renamed it. Sorry about that.

2022-07-14 08:55 UTC, IvayloSlavchev commented on client/src/components/SignIn/SignIn.js
> +                                onChange={(e) => setUsernameOrEmail(e.target.value)}
Fixed

2022-07-14 08:56 UTC, IvayloSlavchev commented on client/src/components/SignIn/SignIn.js
> +                                onChange={(e) => setPassword(e.target.value)}
Fixed

2022-07-14 08:56 UTC, IvayloSlavchev commented on client/src/components/SignUp/Inputs.js
> +                            onChange={(e) => setFirstName(e.target.value)}
Fixed

2022-07-14 08:56 UTC, IvayloSlavchev commented on client/src/components/SignUp/Inputs.js
> +                            onChange={(e) => setLastName(e.target.value)}
Fixed

2022-07-14 08:56 UTC, IvayloSlavchev commented on client/src/components/SignUp/Inputs.js
> +                            onChange={(e) => setEmailReg(e.target.value)}
Fixed

2022-07-14 08:56 UTC, IvayloSlavchev commented on client/src/components/SignUp/Inputs.js
> +                            onChange={(e) => setUsernameReg(e.target.value)}
Fixed

2022-07-14 08:56 UTC, IvayloSlavchev commented on client/src/components/SignUp/Inputs.js
> +                            onChange={(e) => setPasswordReg(e.target.value)}
Fixed

2022-07-14 10:38 UTC, Arabadzhiew approved these changes

2022-07-14 10:55 UTC, petya0111 reviewed
...

2022-07-14 10:57 UTC, petya0111 reviewed
If mac allows me to test this backend I will approve :)  @Arabadzhiew  @IvayloSlavchev

2022-07-14 10:58 UTC, IvayloSlavchev commented
Ok, if you need some help dm me, we can try to fix it (again😆)

2022-07-14 12:22 UTC, JordanRad approved these changes

2022-07-14 12:22 UTC, JordanRad commented on server/models/User.js
> +            type: Sequelize.DataTypes.ENUM('User', 'Admin', 'Custumer Support'),
Typo: **Customer Support**

2022-07-16 17:54 UTC, petya0111 requested changes
* Fix autofill function for registration
* consider password length for sql script fix - hashing function (possible solution password hash block datatype suggested by @Arabadzhiew )
* try to make consisting database names fixes-  
exordium-eshop 
```
 ExordiumDatabase.sql  
.env-example
db.config.js

```

2022-07-20 12:22 UTC, petya0111 approved these changes
Looking good. Great work! ✓

2022-07-20 12:26 UTC, merged