Added new models in folder models.
Exordium-Project/e-shop pull request #42
Opened 2022-07-19 16:26 UTC by Medikko

2022-07-20 06:57 UTC, JordanRad reviewed
LGTM

2022-07-20 06:57 UTC, JordanRad commented on server/models/Image.js
> +       reference_img: {
You may use **image_url** here instead of **reference_img**

2022-07-20 06:57 UTC, JordanRad approved these changes

2022-07-20 08:58 UTC, IvayloSlavchev requested changes

2022-07-20 08:58 UTC, IvayloSlavchev commented on server/models/Basket.js
> +            type: Sequelize.INTEGER,
I think you should add DataTypes after Sequelize in order to work, because me and @Arabadzhiew were facing this type of problem.

2022-07-20 08:58 UTC, IvayloSlavchev commented on server/models/BasketItem.js
> +            type: Sequelize.INTEGER,
Same here.

2022-07-20 09:06 UTC, petya0111 requested changes
some propositions about the build-up of the model

2022-07-20 09:06 UTC, petya0111 commented on server/models/Review.js
> +        likes: {
is the likes something like a rating system or favoriting the product? Is it enough to have only integer likes?

2022-07-20 19:19 UTC, Arabadzhiew commented on server/services/UserService.js
> +        bcrypt.hash(userData.password, SALT_ROUNDS, (err, hash) => {
This function call should be handled in an asynchronous way. I think @IvayloSlavchev added that with his last merge to dev.

2022-07-20 19:24 UTC, IvayloSlavchev commented on server/services/UserService.js
> +        bcrypt.hash(userData.password, SALT_ROUNDS, (err, hash) => {
Yes, but if you think that there is a shorter solution you can change it.

2022-07-21 06:03 UTC, petya0111 requested changes
Resolve conflicts and update your branch with the new dev, in order to merge it.

2022-07-21 09:40 UTC, IvayloSlavchev requested changes
You should pull after every merge. I did this changes in the User/UserService and that's why we have conflicts.

2022-07-24 07:41 UTC, petya0111 approved these changes
Looks good to me.

2022-07-24 16:15 UTC, IvayloSlavchev approved these changes
LGTM!

2022-07-24 16:51 UTC, Arabadzhiew approved these changes

2022-07-24 17:28 UTC, merged