Team page proposal
Exordium-Project/e-shop pull request #44
Opened 2022-07-29 19:46 UTC by petya0111

This is not a final pull request but a proposal for a better story of the project we are working on :)

2022-07-30 06:37 UTC, dplamenov commented on client/src/components/Header/Team/TeamHistory.js
> +                <Team></Team>
Use self-closing tag.

2022-07-30 06:37 UTC, dplamenov commented on client/src/components/Header/Header.js
> +                <CodeIcon></CodeIcon>
Use self-closing tag.

2022-07-30 06:39 UTC, dplamenov commented on client/src/components/Header/Header.js
> +              languages.map((item, index) => {
Rename var to `language` instead `item`

2022-07-30 14:37 UTC, Arabadzhiew requested changes

2022-07-30 14:37 UTC, Arabadzhiew commented on client/src/components/Header/Team/Team.js
> +            linkedin: "https://github.com/IvayloSlavchev",
Here we should have the url for Ivaylo's LinkedIn.

2022-07-30 14:47 UTC, Arabadzhiew commented
@petya0111 I think for the image sources, we should host our own ones, or at least use a more reliable provider. Because, let's say that someone changes their profile picture on GitHub, then the url that we are relying on might no longer work.

2022-07-30 14:55 UTC, IvayloSlavchev requested changes

2022-07-30 14:55 UTC, IvayloSlavchev commented on client/src/components/Header/Team/Team.js
>          },
@Medikko is a Back-End developer

2022-07-30 14:55 UTC, IvayloSlavchev commented on client/src/components/Header/Team/Team.js
>          },
@Arabadzhiew is a Full-Stack developer and also you should provide a link to his LinkedIn account.

2022-07-31 07:11 UTC, JordanRad approved these changes

2022-07-31 07:12 UTC, JordanRad commented on client/src/components/Header/Team/Team.js
>          },
I am also a full-stack developer, but that's a minor detail at this point

2022-07-31 11:50 UTC, petya0111 commented on client/src/components/Header/Team/TeamHistory.js
> +                <Team></Team>
Fixed Team self closing tag ✓ @dplamenov

2022-07-31 11:51 UTC, IvayloSlavchev approved these changes
Good job, @petya0111!

2022-07-31 11:51 UTC, petya0111 commented on client/src/components/Header/Header.js
> +                <CodeIcon></CodeIcon>
Fixed CodeIcon self-closing tag ✓ @dplamenov

2022-07-31 11:51 UTC, petya0111 commented on client/src/components/Header/Header.js
> +              languages.map((item, index) => {
Fixed languageItem variable name ✓ @dplamenov

2022-07-31 11:52 UTC, petya0111 commented on client/src/components/Header/Team/Team.js
> +            linkedin: "https://github.com/IvayloSlavchev",
Fixed Ivaylo's Linkedin ✓ @Arabadzhiew

2022-07-31 11:53 UTC, petya0111 commented on client/src/components/Header/Team/Team.js
>          },
Fixed roles ✓ @IvayloSlavchev  @JordanRad

2022-07-31 17:39 UTC, Arabadzhiew approved these changes
Good work

2022-08-01 10:00 UTC, petya0111 commented on client/src/components/Header/Team/TeamHistory.js
> +                <Team></Team>
@dplamenov  I am curious to know what is your nickname in discord :)

2022-08-01 10:56 UTC, dplamenov commented on client/src/components/Header/Team/TeamHistory.js
> +                <Team></Team>
DimitarDimitrov#4430

2022-08-01 13:28 UTC, fbozhkov approved these changes
Great work Petya! We just need to find an elegant way to incorporate the team button.

2022-08-07 18:43 UTC, IvayloSlavchev approved these changes
I think we can merge it. Btw we have to do some styling at first place, but I think that I can handle some tasks. For now everything seems good. Great job, @petya0111!

2022-08-08 09:33 UTC, JordanRad requested changes
Great work! I've made some short comments regarding minor details

2022-08-08 09:33 UTC, JordanRad commented on server/controllers/Users.js
> +    console.log("int the endpoint check username")
please, remove the console.log

2022-08-08 09:33 UTC, JordanRad commented on server/controllers/Users.js
> +usersController.get('/check-username/{username}', async (req, res) => {
```suggestion
usersController.get('/username/{username}', async (req, res) => {
```
You might just proceed with /username/{username}. Implicitly, a GET request checks if a given resource is present or not

2022-08-08 09:33 UTC, JordanRad commented on server/controllers/Users.js
> +usersController.get('/check-username/{username}', async (req, res) => {
Avoid using verbs within an API path. Refer to this: https://restfulapi.net/resource-naming/

2022-08-08 09:33 UTC, JordanRad commented on server/services/UserService.js
> +    }
You can simply check only if a user with a given username exists. You are not expected to face a situation in which a user has username as property and empty email.

2022-08-10 07:31 UTC, petya0111 commented on server/controllers/Users.js
> +    console.log("int the endpoint check username")
this is out of scope from team page

2022-08-10 07:31 UTC, petya0111 commented on server/controllers/Users.js
> +usersController.get('/check-username/{username}', async (req, res) => {
this is out of scope from team page

2022-08-10 07:31 UTC, petya0111 commented on server/services/UserService.js
> +    }
this is out of scope from team page

2022-08-10 07:32 UTC, merged