Connected_SignIn_With_Back-End
Exordium-Project/e-shop pull request #46
Opened 2022-08-03 15:56 UTC by IvayloSlavchev

This is not final PR, we have to fix the UserService and now I see that I have conflicts.

2022-08-03 17:28 UTC, petya0111 requested changes
Good work for checking and validating data conditionally and proper creation of endpoints. Regex matching can help you to take the exact wanted fields like email or username. Just try it and I promise it will be cool.

2022-08-03 17:28 UTC, petya0111 commented on client/src/components/SignIn/SignIn.js
> +        if (!loginMethod.includes('@')) {
detecting email can easily be made by regex :)

2022-08-03 17:28 UTC, petya0111 commented on client/src/components/SignIn/SignIn.js
> +        } else {
also, username can be detected by regex. Let's try this :)

2022-08-03 17:33 UTC, petya0111 requested changes

2022-08-03 17:33 UTC, petya0111 commented on client/src/components/SignIn/SignIn.js
> +                username: loginMethod,
Someone can input their email with the first letter uppercase. We can make a favor for the user and lowercase all letters before sending them to the backend.

2022-08-03 17:41 UTC, dplamenov commented on client/src/components/SignIn/SignIn.js
> +                console.log(response)
remove console.log

2022-08-03 17:41 UTC, dplamenov commented on client/src/components/SignIn/SignIn.js
> +                console.log(response)
remove console.log

2022-08-03 17:42 UTC, dplamenov commented on server/controllers/Users.js
> +        let isMatch = bcrypt.compareSync(req.body.password, email.password)
make `isMatch` const

2022-08-03 17:43 UTC, dplamenov commented on server/controllers/Users.js
> +        let isMatch = bcrypt.compareSync(req.body.password, username.password)
use const

2022-08-04 17:04 UTC, Arabadzhiew commented on client/src/components/SignIn/SignIn.js
> +    const { register, control, formState: { errors }, handleSubmit } = useForm()
Please use a semicolon at the end of each line.

2022-08-04 17:07 UTC, Arabadzhiew commented on client/src/components/SignIn/SignIn.js
> +                                onChange={(e) => { setLoginMethod(e.target.value) }}
Please don't use single character argument names. Here 'e' can be called 'event'

2022-08-04 17:07 UTC, Arabadzhiew commented on client/src/components/SignIn/SignIn.js
> +                                onChange={(e) => { setUserPassword(e.target.value) }}
Same as above

2022-08-04 17:13 UTC, Arabadzhiew commented on server/config/db.config.js
> +    operatorsAliases: 0,
I thing the operationAliases property can be deleted.

2022-08-04 17:15 UTC, Arabadzhiew commented on client/src/components/SignIn/SignIn.js
> +    const [error, setError] = useState(false)
I think that we can use a better name for the error useState hook. For example isErrorPresent and setErrorPresent for the setter.

2022-08-08 09:40 UTC, JordanRad requested changes

2022-08-08 09:40 UTC, JordanRad commented on client/src/components/SignIn/SignIn.js
> -        Axios.post('http://localhost:3004/api/users/login', {
Please, do not hardcode the url

2022-08-08 09:40 UTC, JordanRad commented on client/src/components/SignIn/SignIn.js
> +            await Axios.post('http://localhost:3004/api/users/check-email/:email', {
Please, do not hardcode the url

2022-08-08 09:40 UTC, JordanRad commented on client/src/components/SignIn/SignIn.js
> +                                onChange={(e) => { setLoginMethod(e.target.value) }}
Agree, either stick with one letter variables for events like ```e```, or just type ```event``` everywhere. Doesn't matter much, but improves consistency of the code

2022-08-08 09:40 UTC, JordanRad commented on client/src/components/SignIn/SignIn.js
> +                            } */}
Please, remove the commented code

2022-08-08 09:40 UTC, JordanRad commented on server/controllers/Users.js
> +usersController.post('/check-email/:email', async (req, res) => {
```suggestion
usersController.post('/email/:email', async (req, res) => {
```
Implicitly, it's enough to write the path like this. You can refer to this article https://restfulapi.net/resource-naming/

2022-08-08 09:40 UTC, JordanRad commented on server/controllers/Users.js
> +usersController.post("/check-username/:username", async (req, res) => {
Same here

2022-08-08 09:40 UTC, JordanRad commented on server/services/UserService.js
> +    // }
Please, remove the commented code

2022-08-13 15:01 UTC, IvayloSlavchev commented on client/src/components/SignIn/SignIn.js
> +        if (!loginMethod.includes('@')) {
Fixed

2022-08-13 15:02 UTC, IvayloSlavchev commented on client/src/components/SignIn/SignIn.js
> +        } else {
Fixed

2022-08-13 15:02 UTC, IvayloSlavchev commented on client/src/components/SignIn/SignIn.js
> +                username: loginMethod,
Fixed

2022-08-13 15:02 UTC, IvayloSlavchev commented on client/src/components/SignIn/SignIn.js
> +                console.log(response)
Fixed

2022-08-13 15:02 UTC, IvayloSlavchev commented on client/src/components/SignIn/SignIn.js
> +                console.log(response)
Fixed

2022-08-13 15:03 UTC, IvayloSlavchev commented on server/controllers/Users.js
> +        let isMatch = bcrypt.compareSync(req.body.password, email.password)
Fixed

2022-08-13 15:03 UTC, IvayloSlavchev commented on client/src/components/SignIn/SignIn.js
> +    const { register, control, formState: { errors }, handleSubmit } = useForm()
Fixed

2022-08-13 15:05 UTC, petya0111 approved these changes
Great work with a fully working flow of a sign-in user with username or email and password validation. It was a great experience for me also! ✅

2022-08-13 17:31 UTC, petya0111 approved these changes

2022-08-16 10:08 UTC, JordanRad approved these changes

2022-08-16 10:31 UTC, petya0111 requested changes

2022-08-16 10:31 UTC, petya0111 commented on server/controllers/Users.js
> +    const response = await UserService.checkUsernameOrEmail(req.params['usernameOrEmail'], res);
here you can add req.params['usernameOrEmail'].toLowerCase(); 
to ensure the user is entering every time the same username no matter the upper or lowercase. 
If it is not fixed now, it will remain a bug.

2022-08-17 11:28 UTC, dplamenov requested changes

2022-08-17 11:28 UTC, dplamenov commented on client/src/components/SignIn/SignIn.js
> +        }
This can be simplified. Extract data into separate constant. And fill username or email property based on condition.

2022-08-17 11:28 UTC, dplamenov commented on client/src/components/SignIn/SignIn.scss
> +            //width: 100%;
remove comment

2022-08-17 14:11 UTC, merged