Ex39/add data fetching logic to product card
Exordium-Project/e-shop pull request #47
Opened 2022-08-14 12:36 UTC by fbozhkov

Combined EX[38,39,40,46]

1. EX38 Add data fetching logic to SpecialCard
2. EX39 Add data fetching logic to ProductCard
3. EX40 Add data fetching logic to SearchBar
4. EX46 Create mock data sql/sequelize script (types/brands/products) with help from @petya0111 

- edits to README.md explaining how to load the mock data 
- added i18next to package.json

2022-08-14 13:31 UTC, dplamenov requested changes

2022-08-14 13:31 UTC, dplamenov commented on client/src/components/main-layout/mainPage.js
> +    const [products, getProducts] = useState('');
rename `getProducts` to `setProducts`

2022-08-14 13:31 UTC, dplamenov commented on client/src/components/main-layout/mainPage.js
> +            getProducts(response.data);
rename `getProducts` to `setProducts`

2022-08-14 13:31 UTC, dplamenov commented on client/src/components/main-layout/mainPage.js
> +import {useTranslation} from "react-i18next";
import axios and react-i18next before local file imports

2022-08-14 13:31 UTC, dplamenov commented on client/src/components/main-layout/mainPage.js
> +    const [products, getProducts] = useState('');
default value must be empty array []

2022-08-14 13:31 UTC, dplamenov commented on client/src/components/main-layout/mainPage.js
> +    const categoryURL = url + '/api/types';
use string template literals

2022-08-14 13:31 UTC, dplamenov commented on client/src/components/product-list/ProductList.js
> +import React, { useEffect, useState } from 'react';
same issues from ProductCars.js

2022-08-14 13:31 UTC, dplamenov commented on client/src/components/product-list/ProductList.js
> +    let {t} = useTranslation()
make this const

2022-08-14 13:31 UTC, dplamenov commented on client/src/components/product-list/ProductList.js
> +        <ProductCard {...productData} /> );
fix code format

2022-08-14 13:31 UTC, dplamenov commented on client/src/components/search-bar/search-bar.js
> +    Object.keys(categories).forEach(key => arr.push({name: key, value: categories[key]}));
use map instead forEach: 

`
const arr = Object.keys(categories).map(key => ({name: key, value: categories[key]}));
`

2022-08-15 11:03 UTC, fbozhkov commented
Changes made @dplamenov

2022-08-15 13:02 UTC, petya0111 approved these changes
Great work for building it up altogether! ✔

2022-08-15 18:38 UTC, JordanRad approved these changes

2022-08-16 10:05 UTC, JordanRad approved these changes

2022-08-17 08:39 UTC, merged