Refactor-ProductCard
Exordium-Project/e-shop pull request #48
Opened 2022-08-17 14:43 UTC by IvayloSlavchev

2022-08-17 14:44 UTC, JordanRad approved these changes

2022-08-17 17:56 UTC, Arabadzhiew approved these changes

2022-08-17 19:23 UTC, petya0111 requested changes
The icon button needs to be improved.

2022-08-17 19:23 UTC, petya0111 commented on client/src/components/product-card/ProductCard.js
> +import "./product-card.scss"
```
import { IconButton } from '@mui/material';
import AddShoppingCartIcon from '@mui/icons-material/AddShoppingCart';
```

2022-08-17 19:23 UTC, petya0111 commented on client/src/components/product-card/ProductCard.js
> +            <Button className="button">+</Button>
Please add a more accurate icon and stylize it to look more closer to the design
```
<IconButton className="button" sx={{ color: 'white', backgroundColor: 'rgba(69,37,242,1)'}}>
     <AddShoppingCartIcon>
     </AddShoppingCartIcon> 
</IconButton>
```

2022-08-17 19:32 UTC, petya0111 requested changes

2022-08-17 19:32 UTC, petya0111 commented on client/src/components/product-card/ProductCard.js
>              <img src="http://www.foaminsulationni.com/images/placeholder/600x600.gif" alt="Image" className='productImage' />
We should consider adding an image URL to the product model, to have a more completed design on the product page.

2022-08-20 12:35 UTC, petya0111 approved these changes
Let's leave it as it is, I will do this in other task.

2022-08-20 12:35 UTC, merged