First iteration of the ShoppingCart component
Exordium-Project/e-shop pull request #50
Opened 2022-08-21 14:53 UTC by Arabadzhiew

This pull request contains the first basic version of the ShoppingCart component. It is **not** the final PR for the task.

2022-08-21 17:23 UTC, petya0111 requested changes
Please use the unified currency for products. Because on the main page is a dollar sign. We can use USD for example.

2022-08-21 19:36 UTC, petya0111 requested changes

2022-08-21 19:36 UTC, petya0111 commented on client/src/components/Header/ShoppingCart/CartItem/cart-item.js
> +                <p>{t('ShoppingCart.CartItem.quantityLabel')}{props.quantity}</p>
Quantity can be dropdown and precalculating prices.

2022-08-22 06:09 UTC, dplamenov requested changes

2022-08-22 06:09 UTC, dplamenov commented on client/src/components/Header/ShoppingCart/shopping-cart.js
> +    })
Use reduce instead forEach.

```
const productsPrice = products.reduce((productsPrice, product) => {  
  return productsPrice + product.price * product.quantity;
})
```

2022-08-22 06:09 UTC, dplamenov commented on client/src/components/Header/ShoppingCart/shopping-cart.js
> +                        <CartItem {...product}/>
key?

2022-08-22 07:11 UTC, IvayloSlavchev requested changes

2022-08-22 07:11 UTC, IvayloSlavchev commented on client/src/components/Header/ShoppingCart/Summary/summary.js
> +        <div className={styles.summaryContainer}>
Please try to use MUI Typography instead of div.

2022-08-22 07:33 UTC, JordanRad commented on client/src/components/Header/ShoppingCart/CartItem/cart-item.js
> +                <p>{t('ShoppingCart.CartItem.quantityLabel')}{props.quantity}</p>
Or an input between ```-``` and ```+``` icons

2022-08-22 07:42 UTC, JordanRad requested changes

2022-08-22 07:42 UTC, JordanRad commented on client/src/components/Header/ShoppingCart/shopping-cart.js
> +    })
Maybe the products should first be grouped by product id/name first

2022-08-27 12:19 UTC, Arabadzhiew commented on client/src/components/Header/ShoppingCart/CartItem/cart-item.js
> +                <p>{t('ShoppingCart.CartItem.quantityLabel')}{props.quantity}</p>
- and + buttons with the state management for them have been added. I have not yet made the quantity filed an input, as I am still not sure whether this is a good design decision.

2022-08-27 12:20 UTC, petya0111 approved these changes

2022-08-27 12:20 UTC, Arabadzhiew commented on client/src/components/Header/ShoppingCart/shopping-cart.js
> +    })
Refactored. We are now using `products.reduce`.

2022-08-27 12:20 UTC, Arabadzhiew commented on client/src/components/Header/ShoppingCart/shopping-cart.js
> +                        <CartItem {...product}/>
Added.

2022-08-27 12:21 UTC, Arabadzhiew commented on client/src/components/Header/ShoppingCart/Summary/summary.js
> +        <div className={styles.summaryContainer}>
What benefit are we gaining by using the MUI `Box` component?

2022-08-27 12:22 UTC, Arabadzhiew commented on client/src/components/Header/ShoppingCart/shopping-cart.js
> +    })
Before calculating the total price?

2022-09-03 00:34 UTC, fbozhkov commented on client/src/components/Header/ShoppingCart/CartItem/cart-item.js
> +                <b>{props.name}</b>
Try to wrap all the text with MUI Typography component

2022-09-03 00:50 UTC, fbozhkov commented on client/src/components/Header/ShoppingCart/shopping-cart.js
> +        <div className={styles.shoppingCart}>
I think better responsiveness can be achieved with MUI Grid. That way it can scale equaly with the Header component on smaller resolutions. You can also centre the whole shopping-card component for a clean view.

2022-09-03 17:11 UTC, IvayloSlavchev commented on client/src/components/Header/ShoppingCart/Summary/summary.js
> +        <div className={styles.summaryContainer}>
Because Box is the equivalent of div and it just going to make the code look a lot more nicer.

2022-09-18 05:12 UTC, IvayloSlavchev approved these changes

2022-09-20 00:44 UTC, fbozhkov commented
401328e and 713a43d
1. Added state management with redux
2. "Add to cart" buttons now work both in main page and product page
3. Select size now works
4. When adding a clothing product form main page a alert window pops up, prompting the user to select a size first and redirects to the product page.

Although not in a very elegant way, point 4. solves the problem of not passing a size to the cart item of type clothing. I am thinking about replacing the alert and redirect with a styled pop-up window where the user can select the size and add to cart, but I am **open to other suggestions**.

What still needs to be done:

- [ ] Style the cart component to the likes of the mockup
- [ ] Add some visual interaction when adding an item to the cart (also **open to suggestions**)
- [ ] Pop-up window or other solution for point 4.
- [ ] Change the quantity of items available (mark as reserved if last size/item)

2022-09-20 06:34 UTC, petya0111 requested changes
Main page has also button for adding to cart, maybe if we have clothes we should choose sizes first and be redirected in ProductPage

2022-09-20 06:34 UTC, petya0111 commented on client/src/components/product-card/ProductCard.js
> +    const productCategory = category[props.typeId - 1]?.name;
you can use the joined table category in productId response it has also property name

2022-09-20 06:43 UTC, petya0111 commented on client/src/components/product-card/ProductCard.js
> +    const productCategory = category[props.typeId - 1]?.name;
Oh I see that it is a old code, you should update with dev branch @fbozhkov

2022-10-04 17:07 UTC, petya0111 approved these changes
@fbozhkov  After updating with dev all should be looking fine. Great work!

2022-10-07 12:35 UTC, merged