Added MUI components to special product card, and fixed header buttons
Exordium-Project/e-shop pull request #51
Opened 2022-08-22 08:44 UTC by IvayloSlavchev

This is not final commit to this PR. We have to set special products from Back-End. For now i only addded MUI components and fixed header buttons.

2022-08-22 12:26 UTC, petya0111 commented on client/src/components/Header/Styles/Header.scss
> +        border-right: none;
border-right or border-radius: none ?

2022-08-22 12:29 UTC, IvayloSlavchev commented on client/src/components/Header/Styles/Header.scss
> +        border-right: none;
I removed border-right, because header buttons have 1px  border and when we use flexbox at the right side it looks like it have 2px or more.

2022-08-22 16:26 UTC, petya0111 requested changes
Please inspect font sizes and font family for the header. I have purposed you some changes. From my comments now it is looking like the screenshot below.
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/13080328/185971156-8bf62bc7-86bd-4697-994e-715f93011273.png">

2022-08-22 16:26 UTC, petya0111 commented on client/src/components/Header/Styles/Header.scss
>          color: black;
add different font 
```
.pages {
    font-family: Roboto;
    font-size: 17px;
}
```

2022-08-22 16:26 UTC, petya0111 commented on client/src/components/Header/Header.js
>              <Link to='/toys' style={textDecorationObject}>
I think the font looks very well. I have inspect it from Mainpage.html

38 line>>
```
<Typography sx={{ fontFamily: 'Montserrat', fontSize: '17px', ml: '11rem', mt: '-4.4rem', color: 'white' }}>
                EXORDIUM
                <Typography sx={{ color: 'rgb(122, 122, 122)', fontSize: '14px' }}>ALL DAY STORE</Typography>
              </Typography>
```

2022-08-22 17:08 UTC, petya0111 requested changes

2022-08-22 17:08 UTC, petya0111 commented on client/src/components/special-components/SpecialComponent.module.scss
> +    text-transform: uppercase;
Texts are not uppercase in a special components.

2022-08-22 17:11 UTC, petya0111 requested changes

2022-08-22 17:11 UTC, petya0111 commented on client/src/components/Header/Styles/Header.scss
>      background-color: rgba(29, 30, 31, 1);
Language dropdown has an additional border. Please remove it.

2022-08-22 17:17 UTC, petya0111 commented on client/src/components/Header/Styles/Header.scss
> +        border-right: none;
You can remove border left then.

2022-08-26 06:00 UTC, JordanRad approved these changes

2022-08-31 16:18 UTC, IvayloSlavchev commented on client/src/components/Header/Styles/Header.scss
> +        border-right: none;
Fixed

2022-08-31 16:18 UTC, IvayloSlavchev commented on client/src/components/Header/Styles/Header.scss
>          color: black;
Fixed

2022-08-31 16:19 UTC, IvayloSlavchev commented on client/src/components/special-components/SpecialComponent.module.scss
> +    text-transform: uppercase;
Fixed

2022-08-31 16:47 UTC, IvayloSlavchev commented on client/src/components/Header/Styles/Header.scss
>      background-color: rgba(29, 30, 31, 1);
Fixed

2022-08-31 16:56 UTC, petya0111 approved these changes
Great looking header and nice work!

2022-09-01 18:35 UTC, Arabadzhiew approved these changes

2022-09-02 08:26 UTC, merged