Login-And-Registration-Flow
Exordium-Project/e-shop pull request #52
Opened 2022-09-06 14:34 UTC by IvayloSlavchev

2022-09-06 17:41 UTC, petya0111 approved these changes
Looking good! ✓

2022-09-06 19:07 UTC, Arabadzhiew commented on client/src/components/Header/Header.js
> +                </Button>
This ternary will be easier to read if the two JSX values are declared as constants and accesed trough them in the expression.

2022-09-06 19:08 UTC, Arabadzhiew commented on client/src/components/SignUp/Inputs.js
> +                    }
Same as above. Export the JSX in constants and access it trough them.

2022-09-07 08:26 UTC, JordanRad approved these changes

2022-09-07 12:07 UTC, IvayloSlavchev commented on client/src/components/Header/Header.js
> +                </Button>
Fixed

2022-09-07 12:07 UTC, IvayloSlavchev commented on client/src/components/SignUp/Inputs.js
> +                    }
Fixed

2022-09-07 17:58 UTC, fbozhkov requested changes
Please change the message "Password should be at least 8 characters long" to show all the requirements for the password ( at least one capital letter, and a number). Right now it isn't very clear what the password should include and leads to confusion if the user gives a pasword like '12345678' for example.

2022-09-07 18:45 UTC, dplamenov commented on client/src/components/SignIn/SignIn.js
> +                                    !isLogged ? notAcceptedLoginRequest : loginButton
it is better to remove `!`

isLogged ? loginButton : notAcceptedLoginRequest

2022-09-08 13:17 UTC, IvayloSlavchev commented on client/src/components/SignIn/SignIn.js
> +                                    !isLogged ? notAcceptedLoginRequest : loginButton
Done

2022-09-08 13:18 UTC, IvayloSlavchev commented
> Please change the message "Password should be at least 8 characters long" to show all the requirements for the password ( at least one capital letter, and a number). Right now it isn't very clear what the password should include and leads to confusion if the user gives a pasword like '12345678' for example.

Done

2022-09-08 14:43 UTC, fbozhkov approved these changes

2022-09-08 14:44 UTC, merged